# 조건에 부합하는 중고거래 댓글 조회하기
SELECT BOARD.TITLE, REPLY.BOARD_ID, REPLY.REPLY_ID, REPLY.WRITER_ID, REPLY.CONTENTS, REPLY.CREATED_DATE
FROM USED_GOODS_REPLY AS REPLY
INNER JOIN USED_GOODS_BOARD AS BOARD
ON REPLY.BOARD_ID = BOARD.BOARD_ID
WHERE REPLY.CREATED_DATE 
	BETWEEN '2022-10-01'
	AND '2022-10-30'
GROUP BY REPLY.CREATED_DATE , BOARD.TITLE;