-- 상품 별 오프라인 매출 구하기
SELECT pd.PRODUCT_CODE,
		SUM(off.SALES_AMOUNT) * pd.PRICE AS SALES
FROM PRODUCT as pd
JOIN OFFLINE_SALE as off
on pd.PRODUCT_ID = off.PRODUCT_ID
GROUP BY pd.PRODUCT_CODE
ORDER BY SALES DESC, pd.PRODUCT_CODE